apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shuotu-fun
    component: shuotu-fun-server
    tier: backend
  name: ks-sample-dev
  namespace: shuotu-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: shuotu-fun
      component: shuotu-fun-server
      tier: backend
  template:
    metadata:
      labels:
        app: shuotu-fun
        component: shuotu-fun-server
        tier: backend
    spec:
      containers:
        - name: $APP_NAME
          env:
            - name: NODE_ENV
              value: production
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
