apiVersion: v1
kind: Service
metadata:
  labels:
    app: shuotu-fun
    component: shuotu-fun-server
  name: shuotu-fun-server
  namespace: shuotu-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30861
  selector:
    app: shuotu-fun
    component: shuotu-fun-server
    tier: backend
  sessionAffinity: None
  type: NodePort
